# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"|\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nmax_tokens\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\r\n\x05top_k\x18\x04 \x01(\x05\x12\r\n\x05top_p\x18\x05 \x01(\x02\x12\x12\n\nrequest_id\x18\x06 \x01(\t\"}\n\x10GenerateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x15\n\rprompt_tokens\x18\x02 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x03 \x01(\x05\x12\x15\n\rfinish_reason\x18\x04 \x01(\t\x12\x12\n\nrequest_id\x18\x05 \x01(\t\"L\n\x05Token\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08token_id\x18\x02 \x01(\x05\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x12\x15\n\rfinish_reason\x18\x04 \x01(\t\"\x0f\n\rHealthRequest\"g\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0f\n\x07running\x18\x03 \x01(\x05\x12\x0e\n\x06queued\x18\x04 \x01(\x05\x12\x16\n\x0emax_batch_size\x18\x05 \x01(\x05\x32\xd1\x01\n\tInference\x12\x43\n\x08Generate\x12\x1a.inference.GenerateRequest\x1a\x1b.inference.GenerateResponse\x12@\n\x0eGenerateStream\x12\x1a.inference.GenerateRequest\x1a\x10.inference.Token0\x01\x12=\n\x06Health\x12\x18.inference.HealthRequest\x1a\x19.inference.HealthResponseB-Z+github.com/mini-vllm/gateway/internal/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/mini-vllm/gateway/internal/pb;pb'
  _globals['_GENERATEREQUEST']._serialized_start=30
  _globals['_GENERATEREQUEST']._serialized_end=154
  _globals['_GENERATERESPONSE']._serialized_start=156
  _globals['_GENERATERESPONSE']._serialized_end=281
  _globals['_TOKEN']._serialized_start=283
  _globals['_TOKEN']._serialized_end=359
  _globals['_HEALTHREQUEST']._serialized_start=361
  _globals['_HEALTHREQUEST']._serialized_end=376
  _globals['_HEALTHRESPONSE']._serialized_start=378
  _globals['_HEALTHRESPONSE']._serialized_end=481
  _globals['_INFERENCE']._serialized_start=484
  _globals['_INFERENCE']._serialized_end=693
# @@protoc_insertion_point(module_scope)
